version: '3.8'
services:
      app:
         build: .
         volumes: 
         - ./FIN-Travel-main:/var/www/html/
         ports:
         - 9001:80
         image: app:php
         container_name: php_container
         # command: php -S 127.0.0.1:8001 index.php
         # #docker run --name=php -d -it -p 80:80 --mount type=bind,source='C:\xampp\htdocs\FIN-Travel-main\FIN-Travel-main',target=/app webdevops/php-nginx-dev
         #php -S 127.0.0.1:8001
         #php -S localhost:800 -t FIN-Travel-main/
         
         depends_on: 
         - db


      db:
         container_name: db
         image: mysql
         build:
             context: mysql
             dockerfile: Dockerfile   
         ports: 
         - 3307:3306
         restart: always
         volumes: 
         - ./db-data:/var/lib/mysql
         - ./mysql/fin_travel.sql:/docker-entrypoint-initdb.d/data.sql
         environment:
            MYSQL_DATABASE: fin_travel
            MYSQL_ROOT_PASSWORD: 1234
           

      phpmyadmin:
         image: phpmyadmin
         restart: always
         ports:
         - 9002:80
         environment:
          PMA_HOST: db
         depends_on: 
         - db
            


      