version: '3.8'
services:
      app:
         build: .
         volumes: 
         - .:/var/www/html/
         ports:
         - 800:800
         image: app:php
         container_name: php_container
         command: php -S 127.0.0.1:800
         #php -S localhost:800 -t FIN-Travel-main/
         
         depends_on: 
         - db


      db:
         container_name: db
         image: mysql:5.7
         build:
             context: database
             dockerfile: Dockerfile   
         ports: 
         - 3307:3306
         restart: always
         volumes: 
         - .db-data:/var/lib/mysql
         - ./database/fin_travel.sql:/docker-entrypoint-initdb.d/data.sql
         environment:
            MYSQL_DATABASE: fin_travel
            MYSQL_ROOT_PASSWORD: 1234
           # PMA_HOST: db
            

# version: '3.8'
# services:
#     app:
#         build: .
#         depends_on:
#             - db
#         volumes:
#             - .:/var/www/html/
#         ports:
#             - 8000:8000
#     db:
#         container_name: db
#         image: mysql
#         restart: always
#         environment:
#             MYSQL_ROOT_PASSWORD: 1234
#             MYSQL_DATABASE: fin_travel
#         ports:
#             - "9906:3306"
#     phpmyadmin:
#       image: phpmyadmin/phpmyadmin
#       ports:
#           - '8080:80'
#       restart: always
#       environment:
#           PMA_HOST: db
#       depends_on:
#           - db

      